# Generated by Django 2.2.3 on 2019-07-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
    ]
